export enum RedisKeys {
  MOVIE_DETAIL = 'MOVIE_DETAIL',
  MOVIE_LIST = 'MOVIE_LIST',
  RECOMMENDATION_LIST = 'RECOMMENDATION_LIST',
  MOVIE_RECOMMENDATION_LOCK = 'MOVIE_RECOMMENDATION_LOCK',
  MOVIES_KEYWORDS = 'MOVIES_KEYWORDS',
  RATING_GROUPED_BY_USER = 'RATING_GROUPED_BY_USER',
  RATING_GROUPED_BY_MOVIE = 'RATING_GROUPED_BY_MOVIE',
  MOVIE_X = 'MOVIE_X',
  GENRE_LIST = 'GENRE_LIST',
}
