version: '3.1'

services:

  db:
    image: mysql:8.0
    container_name: movie-recommendation-db
    restart: always
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/mysql

  redis:
    container_name: movie-recommendation-redis
    image: 'redis:alpine'
    ports:
      - "6379:6379"
    command: "redis-server --requirepass ${REDIS_PASSWORD}"

volumes:
  pgdata: